### ISSUE TITLE
Empty file

### ISSUE THREAD

**Issue by smilebasti** [R0g3rT/Traccar_json-to-GPX#1]
Hi,
it looks like a project i just need.
I downloaded the code and tried it but the file has no external data. It looks like this:
```
<?xml version="1.0" encoding="UTF-8" ?>
<gpx version="1.1" creator="smilebasti" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.topografix.com/GPX/1/1" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
<metadata>
<name>smilebasti</name>
<time>2023-02-04T14:58:50.820Z</time>
<desc>Week - Start: 2023-10-30T00:00 - End: 2022-11-07T00:00</desc>
<author>
<name>smilebastin</name>
</author>
</metadata>

<trk>
<name>Week</name>
<desc>test</desc>
<trkseg>

</trkseg>
</trk>
</gpx>
```

Is it still working for you? I am stuck on version 5.0 and the api gpx export is not in this version. Any thoughts on this would be appreciated :)

**Comment by R0g3rT** [comment]
Hello smilebasti,

thanks for using my code.

I tested it with version 5 and it still works, the API was not changed.

In the dates from you, at the end you have a date in the past and that leads to an empty file. 

Please check your input again and make sure that the earliest date must always be the start of the route.

**Comment by smilebasti** [comment]
Hi, thank you for the fast responses.
It still works :)
Not sure how i miss clicked the year.
